begin;

create table if not exists public.scoring_events (
  id bigint generated by default as identity primary key,
  phase text not null,
  event text not null unique,
  points numeric(8,2) not null,
  sort_order integer not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  group_name text not null,
  multiplier numeric(8,2) not null check (multiplier > 0),
  elimination_phase text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.participant_picks (
  participant_id bigint not null references public.participants(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete restrict,
  pick_order smallint not null check (pick_order between 1 and 3),
  primary key (participant_id, team_id),
  unique (participant_id, pick_order)
);

create table if not exists public.team_results (
  id bigint generated by default as identity primary key,
  team_id bigint not null references public.teams(id) on delete cascade,
  label text not null,
  points numeric(8,2) not null default 0,
  display_value text not null,
  category text not null check (category in ('group', 'groupQualification', 'knockout')),
  sort_order integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team_id, label)
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists scoring_events_set_updated_at on public.scoring_events;
create trigger scoring_events_set_updated_at before update on public.scoring_events
for each row execute function public.set_updated_at();
drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at before update on public.teams
for each row execute function public.set_updated_at();
drop trigger if exists participants_set_updated_at on public.participants;
create trigger participants_set_updated_at before update on public.participants
for each row execute function public.set_updated_at();
drop trigger if exists team_results_set_updated_at on public.team_results;
create trigger team_results_set_updated_at before update on public.team_results
for each row execute function public.set_updated_at();
drop trigger if exists app_settings_set_updated_at on public.app_settings;
create trigger app_settings_set_updated_at before update on public.app_settings
for each row execute function public.set_updated_at();

truncate table public.participant_picks, public.team_results, public.participants, public.teams, public.scoring_events restart identity cascade;

insert into public.scoring_events (phase, event, points, sort_order) values
  ('FASE A GIRONI', 'VITTORIA', 3, 1),
  ('FASE A GIRONI', 'PAREGGIO', 1, 2),
  ('FASE A GIRONI', 'QUALIFICATA 1 POSTO', 3, 3),
  ('FASE A GIRONI', 'QUALIFICATA 2 POSTO', 2, 4),
  ('FASE A GIRONI', 'QUALIFICATA 3 POSTO', 1, 5),
  ('FASE AD ELIMINAZIONE', 'QUALIFICAZIONE VITTORIA PARTITA', 5, 6),
  ('FASE AD ELIMINAZIONE', 'QUALIFICAZIONE VITTORIA SUPPLEMENTARI', 5, 7),
  ('FASE AD ELIMINAZIONE', 'QUALIFICAZIONE VITTORIA RIGORI', 4, 8),
  ('FASE AD ELIMINAZIONE', 'ELIMINAZIONE SCONFITTA RIGORI', 1, 9),
  ('FASE AD ELIMINAZIONE', 'VINCENTE FINALE', 5, 10),
  ('FASE AD ELIMINAZIONE', 'PERDENTE FINALE', 1, 11);

insert into public.teams (name, group_name, multiplier, elimination_phase) values
  ('MESSICO','A',3,null),('REP. CECA','A',3,null),('KOREA','A',4,null),('SUDAFRICA','A',5,null),
  ('SVIZZERA','B',2,null),('BOSNIA','B',4,null),('CANADA','B',4,null),('QATAR','B',5,null),
  ('BRASILE','C',1,null),('MAROCCO','C',3,null),('SCOZIA','C',4,null),('HAITI','C',5,null),
  ('USA','D',3,null),('TURCHIA','D',3,'Girone'),('PARAGUAY','D',3,null),('AUSTRALIA','D',4,null),
  ('GERMANIA','E',1,null),('ECUADOR','E',3,null),('COSTA D''AVORIO','E',3,null),('CURACAO','E',5,null),
  ('OLANDA','F',2,null),('GIAPPONE','F',3,null),('SVEZIA','F',3,null),('TUNISIA','F',4,null),
  ('BELGIO','G',2,null),('EGITTO','G',3,null),('IRAN','G',4,null),('NUOVA ZELANDA','G',5,null),
  ('SPAGNA','H',1,null),('URUGUAY','H',2,null),('ARABIA SAUDITA','H',4,null),('CAPO VERDE','H',5,null),
  ('FRANCIA','I',1,null),('NORVEGIA','I',2,null),('SENEGAL','I',3,null),('IRAQ','I',5,null),
  ('ARGENTINA','J',1,null),('AUSTRIA','J',3,null),('ALGERIA','J',4,null),('GIORDANIA','J',5,null),
  ('PORTOGALLO','K',1,null),('COLOMBIA','K',2,null),('CONGO','K',5,null),('UZBEKISTAN','K',5,null),
  ('INGHILTERRA','L',1,null),('CROAZIA','L',2,null),('GHANA','L',4,null),('PANAMA','L',5,null);

insert into public.participants (name) values
  ('NICOLÒ AGOSTINI'),('SIMONE BENITOZZI'),('MARCO BRAMBILLA'),('MATTEO BORGHI'),
  ('MICHELE CATANEO'),('LEONARDO DI CANDIA'),('MIRKO DONNA'),('GIOVANNI GORGOGLIONE'),
  ('STEFANO MANFREDINI'),('ANDREA PACE'),('LUCA SACCHI'),('VICTOR UNTILA'),('GIANCARLO VOLPE');

with picks(participant_name, team_name, pick_order) as (values
  ('NICOLÒ AGOSTINI','CANADA',1),('NICOLÒ AGOSTINI','MAROCCO',2),('NICOLÒ AGOSTINI','SENEGAL',3),
  ('SIMONE BENITOZZI','BELGIO',1),('SIMONE BENITOZZI','MESSICO',2),('SIMONE BENITOZZI','OLANDA',3),
  ('MARCO BRAMBILLA','CROAZIA',1),('MARCO BRAMBILLA','FRANCIA',2),('MARCO BRAMBILLA','USA',3),
  ('MATTEO BORGHI','FRANCIA',1),('MATTEO BORGHI','INGHILTERRA',2),('MATTEO BORGHI','SPAGNA',3),
  ('MICHELE CATANEO','FRANCIA',1),('MICHELE CATANEO','OLANDA',2),('MICHELE CATANEO','USA',3),
  ('LEONARDO DI CANDIA','FRANCIA',1),('LEONARDO DI CANDIA','OLANDA',2),('LEONARDO DI CANDIA','TURCHIA',3),
  ('MIRKO DONNA','BRASILE',1),('MIRKO DONNA','MAROCCO',2),('MIRKO DONNA','NORVEGIA',3),
  ('GIOVANNI GORGOGLIONE','ARGENTINA',1),('GIOVANNI GORGOGLIONE','CROAZIA',2),('GIOVANNI GORGOGLIONE','NORVEGIA',3),
  ('STEFANO MANFREDINI','GIAPPONE',1),('STEFANO MANFREDINI','MAROCCO',2),('STEFANO MANFREDINI','MESSICO',3),
  ('ANDREA PACE','INGHILTERRA',1),('ANDREA PACE','SVIZZERA',2),('ANDREA PACE','TURCHIA',3),
  ('LUCA SACCHI','BOSNIA',1),('LUCA SACCHI','OLANDA',2),('LUCA SACCHI','TURCHIA',3),
  ('VICTOR UNTILA','CROAZIA',1),('VICTOR UNTILA','MAROCCO',2),('VICTOR UNTILA','NORVEGIA',3),
  ('GIANCARLO VOLPE','BRASILE',1),('GIANCARLO VOLPE','FRANCIA',2),('GIANCARLO VOLPE','MAROCCO',3)
)
insert into public.participant_picks (participant_id, team_id, pick_order)
select p.id, t.id, picks.pick_order
from picks
join public.participants p on p.name = picks.participant_name
join public.teams t on t.name = picks.team_name;

with group_points(team_name, points) as (values
  ('MESSICO',6),('REP. CECA',1),('KOREA',3),('SUDAFRICA',1),('SVIZZERA',4),('BOSNIA',1),
  ('CANADA',4),('QATAR',1),('BRASILE',4),('MAROCCO',4),('SCOZIA',3),('HAITI',0),
  ('USA',6),('TURCHIA',0),('PARAGUAY',3),('AUSTRALIA',3),('GERMANIA',6),('ECUADOR',1),
  ('COSTA D''AVORIO',3),('CURACAO',1),('OLANDA',4),('GIAPPONE',4),('SVEZIA',3),('TUNISIA',0),
  ('BELGIO',2),('EGITTO',4),('IRAN',1),('NUOVA ZELANDA',1),('SPAGNA',4),('URUGUAY',2),
  ('ARABIA SAUDITA',1),('CAPO VERDE',2),('FRANCIA',3),('NORVEGIA',3),('SENEGAL',0),('IRAQ',0),
  ('ARGENTINA',3),('AUSTRIA',3),('ALGERIA',0),('GIORDANIA',0),('PORTOGALLO',1),('COLOMBIA',3),
  ('CONGO',1),('UZBEKISTAN',0),('INGHILTERRA',3),('CROAZIA',0),('GHANA',3),('PANAMA',0)
)
insert into public.team_results (team_id, label, points, display_value, category, sort_order)
select t.id, 'Punti Girone', gp.points, gp.points::text, 'group', 1
from group_points gp join public.teams t on t.name = gp.team_name;

insert into public.team_results (team_id, label, points, display_value, category, sort_order)
select id, 'Qualificazione Girone', 3, '3', 'groupQualification', 2
from public.teams where name in ('MESSICO', 'USA', 'GERMANIA');

insert into public.app_settings (key, value) values
('rules', $rules$TEAM BUILDING - MONDIALE TECNOLOGICA

Ogni partecipante sceglie 3 squadre del Mondiale.

A ogni squadra viene assegnato un coefficiente in base alla sua forza sulla carta:
- coefficiente 1 per le squadre favorite;
- coefficiente 5 per le squadre considerate meno favorite.

Durante il torneo ogni squadra guadagna punti in base ai risultati ottenuti nelle varie fasi.
Il punteggio valido per il Totomondiale si calcola cosi:

punti squadra = punti ottenuti nel torneo x coefficiente squadra

Il punteggio di ogni partecipante e' dato dalla somma dei punti delle sue 3 squadre.

Quota di partecipazione: 10 euro.

Premi:
- Primo posto: 70 euro
- Secondo posto: 40 euro
- Terzo posto: 20 euro

In caso di pari merito, i premi delle posizioni coinvolte vengono sommati e divisi in parti uguali tra i partecipanti a pari punti.
Esempio: se i primi due hanno lo stesso punteggio, dividono primo e secondo premio: 55 euro a testa.$rules$)
on conflict (key) do update set value = excluded.value;

alter table public.scoring_events enable row level security;
alter table public.teams enable row level security;
alter table public.participants enable row level security;
alter table public.participant_picks enable row level security;
alter table public.team_results enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "Public read scoring events" on public.scoring_events;
create policy "Public read scoring events" on public.scoring_events for select to anon, authenticated using (true);
drop policy if exists "Public read teams" on public.teams;
create policy "Public read teams" on public.teams for select to anon, authenticated using (true);
drop policy if exists "Public read participants" on public.participants;
create policy "Public read participants" on public.participants for select to anon, authenticated using (true);
drop policy if exists "Public read participant picks" on public.participant_picks;
create policy "Public read participant picks" on public.participant_picks for select to anon, authenticated using (true);
drop policy if exists "Public read team results" on public.team_results;
create policy "Public read team results" on public.team_results for select to anon, authenticated using (true);
drop policy if exists "Public read app settings" on public.app_settings;
create policy "Public read app settings" on public.app_settings for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on public.scoring_events, public.teams, public.participants, public.participant_picks, public.team_results, public.app_settings to anon, authenticated;

commit;
